# Site settings
title: Code for Vallejo
email: vallejo@codeforamerica.org
description: >
  Coding for America, in Vallejo.
baseurl: ""
url: "http://codeforvallejo.org" # the base hostname & protocol for your site
facebook_username: codeforvallejo

# Build settings
markdown: kramdown
permalink: none
